# Generated by Django 4.0.4 on 2022-06-10 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_orderproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderProduct',
        ),
    ]
